substitutions:
  _REGION: us-central1
  _REPO: slack-zoom-reminder
  _JOB: slack-zoom-reminder
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/reminder

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}:${SHORT_SHA}
      - -t
      - ${_IMAGE}:latest
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, "${_IMAGE}"]

  - id: update-job
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - ${_JOB}
      - --image=${_IMAGE}:${SHORT_SHA}
      - --region=${_REGION}

images:
  - ${_IMAGE}:${SHORT_SHA}
  - ${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
